name: Buildalon Unity Setup
description: A GitHub action for setting up the Unity Game Engine for CI/CD workflows.
branding:
  color: red
  icon: download
inputs:
  version-file:
    description: 'Specify a path to search for the unity project version text file. Useful if there are multiple projects in a single repo. Pass `None` if creating a new project to skip file search.'
    required: false
    default: ''
  unity-version:
    description: 'Specify the Unity version(s) to install. example: `2019.4.13f1 (518737b1de84)`. ***This will override any version specified in the `version-file`!***'
    required: false
    default: ''
  build-targets:
    description: 'Specify the build targets to install modules for. One or more of `StandaloneWindows64` `WSAPlayer` `StandaloneOSX` `iOS` `StandaloneLinux64` `Android` `Lumin` `WebGL` `VisionOS`.'
    required: false
    default: ''
  modules:
    description: 'Modules to install with the editor. This list can be different per editor version.'
    required: false
    default: ''
  architecture:
    description: 'Specify the architecture to install. Either `x86_64` or `arm64`.'
    required: false
    default: ''
  install-path:
    description: 'Specify the path where Unity will be installed to.'
    required: false
  auto-update-hub:
    description: 'Automatically update Unity Hub to the latest version before installing Unity Editors. Can be `true` or `false`.'
    required: false
    default: 'true'
  hub-version:
    description: 'Specify a specific version of Unity Hub to install. Example: `3.12.0`. When set, auto-update-hub is automatically disabled.'
    required: false
    default: ''
runs:
  using: node20
  main: dist/index.js
